// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vfpu_tb.h for the primary calling header

#ifndef VERILATED_VFPU_TB___024ROOT_H_
#define VERILATED_VFPU_TB___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"
class Vfpu_tb_fpu_if;


class Vfpu_tb__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vfpu_tb___024root final : public VerilatedModule {
  public:
    // CELLS
    Vfpu_tb_fpu_if* __PVT__fpu_tb__DOT__bus;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ fpu_tb__DOT__clk;
        CData/*0:0*/ fpu_tb__DOT__rst_n;
        CData/*4:0*/ fpu_tb__DOT__rd_o;
        CData/*4:0*/ fpu_tb__DOT__ff;
        CData/*0:0*/ fpu_tb__DOT__fpw;
        CData/*0:0*/ fpu_tb__DOT__intw;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__op_is_addsub;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__op_is_minmax;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__op_is_cmp;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__op_is_fma;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__op_is_sgn;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__op_is_divsqrt;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__op_is_convert;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__sign_a;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__sign_b;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__sign_c;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_nan_a;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_nan_b;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_nan_c;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_qnan_a;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_qnan_b;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_qnan_c;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_snan_a;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_snan_b;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_snan_c;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_inf_a;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_inf_b;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_inf_c;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_zero_a;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_zero_b;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_zero_c;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_subnormal_a;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_subnormal_b;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__is_subnormal_c;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__add_sign;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__add_grs;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__add_rm;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__add_is_nan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__add_is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__add_is_zero;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__add_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT____Vcellinp__u_fadd_sub__valid_in;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__mul_sign;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__mul_grs;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__mul_rm;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__mul_is_nan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__mul_is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__mul_is_zero;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__mul_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT____Vcellinp__u_fmult__valid_in;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__fma_sign_a_eff;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__fma_sign_c_eff;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__fma_sign;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__fma_grs;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__fma_rm;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__fma_is_nan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__fma_is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__fma_is_zero;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__fma_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT____Vcellinp__u_fma__valid_in;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__arith_sign;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__arith_grs;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__arith_rm;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__arith_is_nan;
    };
    struct {
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__arith_is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__arith_is_zero;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__rnd_is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__fpack_of;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__fpack_uf;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__class_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT____Vcellinp__u_fclass__valid_in;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__rd_class;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__minmax_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT____Vcellinp__u_fminmax__valid_in;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__rd_minmax;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__cmp_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT____Vcellinp__u_fcmp__valid_in;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__rd_cmp;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__sgn_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT____Vcellinp__u_fsgn__valid_in;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__rd_sgn;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__divsqrt_sign;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__divsqrt_grs;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__divsqrt_rm;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__divsqrt_is_nan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__divsqrt_is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__divsqrt_is_zero;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__divsqrt_fflags;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__rd_divsqrt;
        CData/*1:0*/ fpu_tb__DOT__dut__DOT__conv_src_fmt;
        CData/*1:0*/ fpu_tb__DOT__dut__DOT__conv_dst_fmt;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__conv_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT____Vcellinp__u_fconvert__valid_in;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__rd_conv;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__conv_is_int_r;
        CData/*7:0*/ fpu_tb__DOT__dut__DOT__u_funpack_a__DOT__exp32;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_funpack_a__DOT__exp16;
        CData/*7:0*/ fpu_tb__DOT__dut__DOT__u_funpack_b__DOT__exp32;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_funpack_b__DOT__exp16;
        CData/*7:0*/ fpu_tb__DOT__dut__DOT__u_funpack_c__DOT__exp32;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_funpack_c__DOT__exp16;
        CData/*3:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__valid_pipe;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__fflags_s1;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__fflags_s2;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__fflags_s3;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s1_sign_a;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s1_sign_b;
        CData/*5:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s1_op;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s1_is_nan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s1_is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s1_inf_sign;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s1_grs;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s1_rm;
        CData/*6:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__shift_amt;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__eff_sign_b;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__inf_minus_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s2_sign;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s2_is_nan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s2_is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s2_inf_sign;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s2_grs;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s2_rm;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s3_sign;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s3_is_nan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s3_is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s3_inf_sign;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s3_grs;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s3_rm;
    };
    struct {
        CData/*3:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__valid_pipe;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s1_sign;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s1_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s1_is_nan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s1_is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s1_is_zero;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s1_rm;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s2_sign;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s2_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s2_is_nan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s2_is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s2_is_zero;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s2_rm;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s3_sign;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s3_grs;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s3_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s3_is_nan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s3_is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s3_is_zero;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s3_rm;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__valid_pipe;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s1_rm;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s1_sign_mul;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s1_sign_c;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s1_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s1_is_nan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s1_is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s1_sign_sp;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s2_rm;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s2_sign_mul;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s2_sign_c;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s2_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s2_is_nan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s2_is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s2_sign_sp;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s3_rm;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s3_sign_big;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s3_sign_small;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s3_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s3_is_nan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s3_is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s3_sign_sp;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s4_rm;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s4_sign;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s4_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s4_is_nan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s4_is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s4_sign_sp;
        CData/*6:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__lz_pos;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fround__DOT__round_up;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fround__DOT__round_carry;
        CData/*6:0*/ fpu_tb__DOT__dut__DOT__u_fpack__DOT__shift;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fclass__DOT__valid_pipe;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__u_fclass__DOT__class_out;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fclass__DOT__sign;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fclass__DOT__is_zero;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fclass__DOT__is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fclass__DOT__is_qnan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fclass__DOT__is_snan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fclass__DOT__is_subnormal;
        CData/*7:0*/ fpu_tb__DOT__dut__DOT__u_fclass__DOT__u_fclassify__DOT__exp32;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fclass__DOT__u_fclassify__DOT__exp16;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fminmax__DOT__valid_pipe;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fminmax__DOT__a_lt_b;
    };
    struct {
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fminmax__DOT__comb_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fcmp__DOT__valid_pipe;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fcmp__DOT__a_eq_b;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fcmp__DOT__a_lt_b;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fcmp__DOT__comb_fflags;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fsgn__DOT__valid_r;
        CData/*1:0*/ fpu_tb__DOT__dut__DOT__u_fdivsqrt__DOT__state;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fdivsqrt__DOT__op_sqrt;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fdivsqrt__DOT__sign_r;
        CData/*6:0*/ fpu_tb__DOT__dut__DOT__u_fdivsqrt__DOT__iter_cnt;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fdivsqrt__DOT__fflags_r;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fdivsqrt__DOT__is_nan_r;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fdivsqrt__DOT__is_inf_r;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fdivsqrt__DOT__is_zero_r;
        CData/*2:0*/ fpu_tb__DOT__dut__DOT__u_fdivsqrt__DOT__rm_r;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__valid_r;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__sign;
        CData/*7:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__exp32;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__exp16;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__is_nan;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__is_inf;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__is_zero;
        CData/*0:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__is_subnormal;
        CData/*4:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__fflags;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__fpu_tb__DOT__clk__0;
        CData/*0:0*/ __VactContinue;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__exp_a;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__exp_b;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__exp_c;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__add_exp;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__mul_exp;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__fma_exp;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__rnd_exp;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__divsqrt_exp;
        SData/*10:0*/ fpu_tb__DOT__dut__DOT__u_funpack_a__DOT__exp64;
        SData/*9:0*/ fpu_tb__DOT__dut__DOT__u_funpack_a__DOT__mant16;
        SData/*10:0*/ fpu_tb__DOT__dut__DOT__u_funpack_b__DOT__exp64;
        SData/*9:0*/ fpu_tb__DOT__dut__DOT__u_funpack_b__DOT__mant16;
        SData/*10:0*/ fpu_tb__DOT__dut__DOT__u_funpack_c__DOT__exp64;
        SData/*9:0*/ fpu_tb__DOT__dut__DOT__u_funpack_c__DOT__mant16;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s1_exp;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__align_diff;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s2_exp;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s3_exp;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s1_exp;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s2_exp;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s3_exp;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s1_exp_mul;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s1_exp_c;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s2_exp_mul;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s2_exp_c;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s3_exp;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s4_exp;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s5_exp;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fround__DOT__renorm_exp;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fpack__DOT__exp_biased;
        SData/*10:0*/ fpu_tb__DOT__dut__DOT__u_fpack__DOT__exp_field;
        SData/*9:0*/ fpu_tb__DOT__dut__DOT__u_fclass__DOT__fclass_mask;
        SData/*10:0*/ fpu_tb__DOT__dut__DOT__u_fclass__DOT__u_fclassify__DOT__exp64;
        SData/*9:0*/ fpu_tb__DOT__dut__DOT__u_fclass__DOT__u_fclassify__DOT__mant16;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fdivsqrt__DOT__exp_r;
        SData/*10:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__exp64;
        SData/*9:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__mant16;
    };
    struct {
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__exp_unbiased;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__unnamedblk6__DOT__exp_b;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__unnamedblk7__DOT__exp_b;
        SData/*12:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__unnamedblk8__DOT__exp_b;
        IData/*31:0*/ fpu_tb__DOT__pass_cnt;
        IData/*31:0*/ fpu_tb__DOT__fail_cnt;
        IData/*22:0*/ fpu_tb__DOT__dut__DOT__u_funpack_a__DOT__mant32;
        IData/*22:0*/ fpu_tb__DOT__dut__DOT__u_funpack_b__DOT__mant32;
        IData/*22:0*/ fpu_tb__DOT__dut__DOT__u_funpack_c__DOT__mant32;
        VlWide<4>/*105:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s1_prod;
        VlWide<4>/*105:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s2_prod;
        VlWide<4>/*105:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s1_prod;
        VlWide<4>/*105:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s2_prod;
        VlWide<4>/*105:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s2_mant_c_ext;
        VlWide<4>/*105:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s3_big;
        VlWide<4>/*105:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s3_small;
        VlWide<4>/*106:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s4_sum;
        VlWide<4>/*106:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s5_norm;
        IData/*31:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__unnamedblk1__DOT__i;
        IData/*22:0*/ fpu_tb__DOT__dut__DOT__u_fclass__DOT__u_fclassify__DOT__mant32;
        VlWide<4>/*105:0*/ fpu_tb__DOT__dut__DOT__u_fdivsqrt__DOT__dividend;
        VlWide<4>/*105:0*/ fpu_tb__DOT__dut__DOT__u_fdivsqrt__DOT__divisor;
        VlWide<4>/*105:0*/ fpu_tb__DOT__dut__DOT__u_fdivsqrt__DOT__remainder;
        VlWide<4>/*105:0*/ fpu_tb__DOT__dut__DOT__u_fdivsqrt__DOT__rem_shifted;
        IData/*22:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__mant32;
        IData/*31:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__lz;
        IData/*31:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__unnamedblk3__DOT__i;
        VlWide<3>/*64:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__unnamedblk4__DOT__tmp_mant;
        IData/*31:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__unnamedblk4__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ fpu_tb__DOT__res;
        QData/*52:0*/ fpu_tb__DOT__dut__DOT__mant_a;
        QData/*52:0*/ fpu_tb__DOT__dut__DOT__mant_b;
        QData/*52:0*/ fpu_tb__DOT__dut__DOT__mant_c;
        QData/*54:0*/ fpu_tb__DOT__dut__DOT__add_mant;
        QData/*54:0*/ fpu_tb__DOT__dut__DOT__mul_mant;
        QData/*54:0*/ fpu_tb__DOT__dut__DOT__fma_mant;
        QData/*54:0*/ fpu_tb__DOT__dut__DOT__arith_mant;
        QData/*52:0*/ fpu_tb__DOT__dut__DOT__rnd_mant;
        QData/*63:0*/ fpu_tb__DOT__dut__DOT__arith_result;
        QData/*63:0*/ fpu_tb__DOT__dut__DOT__class_result;
        QData/*63:0*/ fpu_tb__DOT__dut__DOT__minmax_result;
        QData/*63:0*/ fpu_tb__DOT__dut__DOT__cmp_result;
        QData/*63:0*/ fpu_tb__DOT__dut__DOT__sgn_result;
        QData/*54:0*/ fpu_tb__DOT__dut__DOT__divsqrt_mant;
        QData/*63:0*/ fpu_tb__DOT__dut__DOT__conv_result;
        QData/*51:0*/ fpu_tb__DOT__dut__DOT__u_funpack_a__DOT__mant64;
        QData/*51:0*/ fpu_tb__DOT__dut__DOT__u_funpack_b__DOT__mant64;
        QData/*51:0*/ fpu_tb__DOT__dut__DOT__u_funpack_c__DOT__mant64;
        QData/*53:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s1_mant_a;
        QData/*53:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s1_mant_b;
        QData/*53:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__grs_ext;
        QData/*53:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s2_mant;
        QData/*54:0*/ fpu_tb__DOT__dut__DOT__u_fadd_sub__DOT__s3_mant;
        QData/*54:0*/ fpu_tb__DOT__dut__DOT__u_fmult__DOT__s3_mant;
        QData/*52:0*/ fpu_tb__DOT__dut__DOT__u_fma__DOT__s1_mant_c;
        QData/*53:0*/ fpu_tb__DOT__dut__DOT__u_fround__DOT__round_result;
        QData/*51:0*/ fpu_tb__DOT__dut__DOT__u_fpack__DOT__mant_field;
        QData/*52:0*/ fpu_tb__DOT__dut__DOT__u_fpack__DOT__mant_shifted;
        QData/*51:0*/ fpu_tb__DOT__dut__DOT__u_fclass__DOT__u_fclassify__DOT__mant64;
        QData/*63:0*/ fpu_tb__DOT__dut__DOT__u_fminmax__DOT__canonical_nan;
        QData/*63:0*/ fpu_tb__DOT__dut__DOT__u_fminmax__DOT__comb_result;
    };
    struct {
        QData/*55:0*/ fpu_tb__DOT__dut__DOT__u_fdivsqrt__DOT__quotient;
        QData/*51:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__mant64;
        QData/*52:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__mant_norm;
        QData/*63:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__result;
        QData/*63:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__unnamedblk4__DOT__int_val;
        QData/*63:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__unnamedblk4__DOT__abs_val;
        QData/*63:0*/ fpu_tb__DOT__dut__DOT__u_fconvert__DOT__unnamedblk9__DOT__int_res;
        VlUnpacked<CData/*4:0*/, 4> fpu_tb__DOT__dut__DOT__rd_add;
        VlUnpacked<CData/*4:0*/, 4> fpu_tb__DOT__dut__DOT__rd_mul;
        VlUnpacked<CData/*4:0*/, 5> fpu_tb__DOT__dut__DOT__rd_fma;
        VlUnpacked<CData/*0:0*/, 7> __Vm_traceActivity;
    };
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_he2390f0c__0;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vfpu_tb__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vfpu_tb___024root(Vfpu_tb__Syms* symsp, const char* v__name);
    ~Vfpu_tb___024root();
    VL_UNCOPYABLE(Vfpu_tb___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
